apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-controller-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: crd-controller-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: crd-controller-clusterrole
  apiGroup: rbac.authorization.k8s.io
