apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match <plural>.<group>
  name: ephemeralvolumeclaims.crd.dev
spec:
  scope: Namespaced
  group: crd.dev
  names:
    kind: EphemeralVolumeClaim
    plural: ephemeralvolumeclaims
    singular: ephemeralvolumeclaim
    shortNames:
      - evcs
      - evc
  versions:
    - name: v1
      # A boolean that indicates whether this version should be served via the API.
      # If the served flag in a Kubernetes CustomResourceDefinition (CRD) version is set to false,
      # it means that this particular version of the custom resource is not available to be accessed via the Kubernetes API.
      # If a non-served version is also the storage version (which is uncommon and typically not recommended),
      # it means that the data of this version is used internally for storage in etcd, but it cannot be directly accessed or manipulated via the API. Instead, conversions would need to be defined to and from a served version.
      served: true
      # A boolean indicating if this version is the one that should be stored in the etcd database.
      # Only one version can be marked as true for storage.
      # When a version is set as storage: false, existing objects are retained
      # but must be accessed or manipulated through a version marked as storage: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
