apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apiservice-waiter-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: apiservice-waiter
    namespace: default
roleRef:
  kind: ClusterRole
  name: apiservice-waiter-role
  apiGroup: rbac.authorization.k8s.io
