apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiservice-waiter-role
rules:
  - apiGroups: ["apiregistration.k8s.io"]
    resources: ["apiservices"]
    verbs: ["get", "list", "watch"]
