apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-apiservice
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      serviceAccountName: apiservice-waiter
      containers:
        - name: wait-for-apiservice
          image: bitnami/kubectl:1.21
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Waiting for ApiService to be available..."
              kubectl wait --for=condition=Available --timeout=120s apiservice v1alpha1.example.com
      restartPolicy: Never
  backoffLimit: 4

